In [1]:
import pandas as pd
import requests

In [89]:
# LAGT (v1.0.1) dataset directly from Zenodo
resp = requests.get("https://zenodo.org/record/4971946/files/LAGT_v1-0.json?download=1")
LAGT = pd.DataFrame(resp.json())

In [35]:
LAGT.columns

Index(['filename', 'author', 'title', 'wordcount', 'author_id', 'doc_id',
       'raw_date', 'date_avr', 'date_probs', 'date_manual', 'provenience',
       'tlg_epithet', 'clean_string', 'n_sentences', 'lemmatized_sentences'],
      dtype='object')

In [53]:
len(LAGT[LAGT["provenience"]=="christian"])

148

In [91]:
LAGT_metadata = pd.read_csv("../data/LAGT_metadata.csv")
provenience_dict = dict(zip(LAGT_metadata["filename"],  LAGT_metadata["provenience"]))
author_dict = dict(zip(LAGT_metadata["author_id"],  LAGT_metadata["author"]))
LAGT["provenience"] = LAGT["filename"].apply(lambda x: provenience_dict[x])

In [92]:
len(LAGT[LAGT["provenience"]=="christian"])

216

In [93]:
LAGT[(LAGT["provenience"]=="christian") & (LAGT["date_avr"].isnull())]

,filename,author,title,wordcount,author_id,doc_id,raw_date,date_avr,date_probs,date_manual,provenience,tlg_epithet,clean_string,n_sentences,lemmatized_sentences
1194,tlg1750.tlg001.1st1K-grc1.xml,Pseudo-Dorotheus (Vitae Prophetarum),De prophetarum vita et obitu (Dorothei recensio),5347,tlg1750,tlg1750.tlg001,Varia,NaN,{},NaN,christian,[],"Οὗτος Ὠσηὲ τῶν ιβʹ προφητῶν ὁ πρῶτος, ἀξιωθεὶς...",329,"[[ὠσηὲ, προφήτης, πρῶτος, ἀξιωθεὶς, λέγω, δεσπ..."
1195,tlg1750.tlg002.1st1K-grc1.xml,Vitae Prophetarum,De prophetarum vita et obitu (recensio anonyma),4110,tlg1750,tlg1750.tlg002,Varia,NaN,{},NaN,christian,[],αʹ. Ἡσαΐας ἀπὸ Ἱερουσαλὴμ θνήσκει ὑπὸ Μανασσῆ ...,329,"[[], [Ἠσαΐας, Ἱεροσόλυμα, θνήσκω, Μανασσῆς, πρ..."
1196,tlg1750.tlg003.1st1K-grc1.xml,Vitae Prophetarum (Scholius Hesychius),De prophetarum vita et obitu (recensio scholii...,1166,tlg1750,tlg1750.tlg003,Varia,NaN,{},NaN,christian,[],αʹ. Ὠσηὲ ἑρμηνεύεται σωζόμενος. Οὗτος ἦν ἐκ ελ...,105,"[[], [ὠσηὲ, ἑρμηνεύω, σωζόμενος], [ελεμὼθ, φυλ..."
1197,tlg1750.tlg004.1st1K-grc1.xml,Pseudo-Dorotheus (Vitae Prophetarum),Index apostolorum discipulorumque Domini,3616,tlg1750,tlg1750.tlg004,Varia,NaN,{},NaN,christian,[],Δωροθέου ἐπισκόπου Τύρου ἀρχαίου ἀνδρὸς πνευμα...,253,"[[δωροθέου, ἐπίσκοπος, Τύρος, ἀρχαῖος, ἀνήρ, π..."

In [94]:
LAGT = LAGT[LAGT["date_avr"] < 5]

In [56]:
LAGT[LAGT["doc_id"].str.startswith("tlg0031.tlg006")]

,filename,author,title,wordcount,author_id,doc_id,raw_date,date_avr,date_probs,date_manual,provenience,tlg_epithet,clean_string,n_sentences,lemmatized_sentences,sentences_paul,sentences_paul_N
390,tlg0031.tlg006.perseus-grc2.xml,Paul of Tarsus,New Testament - Romans,7107,tlg0031paul,tlg0031.tlg006,A.D. 1,0.5,{'0.5': 1},0.5,christian,[],"ΠΑΥΛΟΣ δοῦλος Ἰησοῦ Χριστοῦ, κλητὸς ἀπόστολος...",490,"[[Παῦλος, δοῦλος, Ἰησοῦς, Χριστός, κλητός, ἀπό...","[[Παῦλος, δοῦλος, Ἰησοῦς, Χριστός, κλητός, ἀπό...",1

In [96]:
LAGT[LAGT["author_id"].str.startswith("tlg0031paul")]

,filename,author,title,wordcount,author_id,doc_id,raw_date,date_avr,date_probs,date_manual,provenience,tlg_epithet,clean_string,n_sentences,lemmatized_sentences
390,tlg0031.tlg006.perseus-grc2.xml,Paul of Tarsus,New Testament - Romans,7107,tlg0031paul,tlg0031.tlg006,A.D. 1,0.5,{'0.5': 1},0.5,christian,[],"ΠΑΥΛΟΣ δοῦλος Ἰησοῦ Χριστοῦ, κλητὸς ἀπόστολος...",490,"[[Παῦλος, δοῦλος, Ἰησοῦς, Χριστός, κλητός, ἀπό..."
391,tlg0031.tlg007.perseus-grc2.xml,Paul of Tarsus,New Testament - 1 Corinthians,6814,tlg0031paul,tlg0031.tlg007,A.D. 1,0.5,{'0.5': 1},0.5,christian,[],ΠΑΥΛΟΣ κλητὸς ἀπόστολος Ἰησοῦ Χριστοῦ διὰ θελ...,544,"[[Παῦλος, κλητός, ἀπόστολος, Ἰησοῦς, Χριστός, ..."
392,tlg0031.tlg008.perseus-grc2.xml,Paul of Tarsus,New Testament - 2 Corinthians,4470,tlg0031paul,tlg0031.tlg008,A.D. 1,0.5,{'0.5': 1},0.5,christian,[],ΠΑΥΛΟΣ ἀπόστολος Χριστοῦ Ἰησοῦ διὰ θελήματος ...,274,"[[Παῦλος, ἀπόστολος, Χριστός, Ἰησοῦς, θέλημα, ..."
393,tlg0031.tlg009.perseus-grc2.xml,Paul of Tarsus,New Testament - Galatians,2235,tlg0031paul,tlg0031.tlg009,A.D. 1,0.5,{'0.5': 1},0.5,christian,[],"ΠΑΥΛΟΣ ἀπόστολος, οὐκ ἀπʼ ἀνθρώπων οὐδὲ διʼ ἀ...",159,"[[Παῦλος, ἀπόστολος, ἄνθρωπος, ἄνθρωπος, Ἰησοῦ..."
395,tlg0031.tlg011.perseus-grc2.xml,Paul of Tarsus,New Testament - Philippians,1631,tlg0031paul,tlg0031.tlg011,A.D. 1,0.5,{'0.5': 1},0.5,christian,[],ΠΑΥΛΟΣ ΚΑΙ ΤΙΜΟΘΕΟΣ δοῦλοι Χριστοῦ Ἰησοῦ πᾶσι...,83,"[[Παῦλος, Τιμόθεος, δοῦλος, Χριστός, Ἰησοῦς, ἅ..."
397,tlg0031.tlg013.perseus-grc2.xml,Paul of Tarsus,New Testament - 1 Thessalonians,1475,tlg0031paul,tlg0031.tlg013,A.D. 1,0.5,{'0.5': 1},0.5,christian,[],ΠΑΥΛΟΣ ΚΑΙ ΣΙΛΟΥΑΝΟΣ ΚΑΙ ΤΙΜΟΘΕΟΣ τῇ ἐκκλησίᾳ...,65,"[[Παῦλος, σιλουανος, Τιμόθεος, ἐκκλησία, Θεσσα..."
402,tlg0031.tlg018.perseus-grc2.xml,Paul of Tarsus,New Testament - Philemon,334,tlg0031paul,tlg0031.tlg018,A.D. 1,0.5,{'0.5': 1},0.5,christian,[],ΠΑΥΛΟΣ δέσμιος Χριστοῦ Ἰησοῦ καὶ Τιμόθεος ὁ ἀ...,17,"[[Παῦλος, δέσμιος, Χριστός, Ἰησοῦς, Τιμόθεος, ..."

In [97]:
def get_word_sentences(sentences_list, word):
    selected_sentences = [sentence for sentence in sentences_list if word in sentence]
    return selected_sentences

In [98]:
word = "Παῦλος"
LAGT["sentences_paul"] = LAGT["lemmatized_sentences"].apply(lambda x: get_word_sentences(x, word))

In [99]:
LAGT["sentences_paul_N"] = LAGT["sentences_paul"].apply(lambda x: len(x))

In [100]:
# how many documents contain the word "Παῦλος"
len(LAGT[LAGT["sentences_paul_N"]>0])

121

In [101]:
LAGT["sentences_paul_N"].sum()

1138

In [62]:
LAGT[LAGT["provenience"]=="christian"]["sentences_paul_N"].sum()

1045

In [102]:
LAGT[(LAGT["provenience"]=="christian") & (LAGT["author_id"]!="tlg0031paul")]["sentences_paul_N"].sum()

1027

In [108]:
df = LAGT[(LAGT["provenience"]=="christian") &(LAGT["author_id"]!="tlg0031paul")]#  ["sentences_paul_N"].sum()

In [109]:
df_authors = df.groupby("author_id").sum()[["wordcount", "n_sentences", "sentences_paul_N"]].sort_values("sentences_paul_N", ascending=False)# 
def get_author(x):
    try:
        return author_dict[x]
    except:
        return None
df_authors.reset_index(inplace=True)
df_authors["author"] = df_authors["author_id"].apply(get_author) 
df_authors.set_index("author", inplace=True)
df_authors.head(20)

,author_id,wordcount,n_sentences,sentences_paul_N
author,,,,
Origenes,tlg2042,931431,110127,459
Luke (the evangelist),tlg0031luke,37864,2234,125
Epiphanius,tlg2021,325038,33079,102
"Socrates, Scholasticus",tlg2057,103901,8743,76
"Sozomenus, Salaminius Hermias",tlg2048,112966,7150,63
Athanasius,tlg2035,94010,10789,49
"Theodoret, Bishop of Cyrus",tlg4089,153333,16094,40
"Basil, Saint, Bishop of Caesarea",tlg2040,144429,11257,23
Clement of Alexandria,tlg0555,235754,14753,18
Eusebius,tlg2018,620546,35220,17
pseudo-Menander,tlg2022,77297,20005,14
Irenaeus,tlg1447,24651,4525,12
Pauline literature,tlg0031pspa,8324,390,10
Hippolytus,tlg2115,69987,4394,7
Polycarp,tlg1622,1804,212,2
Clemens Romanus,tlg1271,13936,1410,2
Dionysius Corinthius,tlg1329,607,67,2
Ignatius Antiochenus,tlg1443,8396,790,2
Marcus Diaconus,tlg2806,24954,2132,1
Philostorgius,tlg2058,37002,4172,1

In [110]:
df_authors["paul_proportion"] = df_authors["sentences_paul_N"] / df_authors["n_sentences"]
df_authors.sort_values("paul_proportion", ascending=False).head(20)

,author_id,wordcount,n_sentences,sentences_paul_N,paul_proportion
author,,,,,
Luke (the evangelist),tlg0031luke,37864,2234,125,0.055953
Dionysius Corinthius,tlg1329,607,67,2,0.029851
Pauline literature,tlg0031pspa,8324,390,10,0.025641
NaN,tlg0031f,1095,42,1,0.023810
Polycarp,tlg1622,1804,212,2,0.009434
"Sozomenus, Salaminius Hermias",tlg2048,112966,7150,63,0.008811
"Socrates, Scholasticus",tlg2057,103901,8743,76,0.008693
Seniores Apud Irenaeum,tlg1665,695,200,1,0.005000
Athanasius,tlg2035,94010,10789,49,0.004542
Origenes,tlg2042,931431,110127,459,0.004168
Epiphanius,tlg2021,325038,33079,102,0.003084
Irenaeus,tlg1447,24651,4525,12,0.002652
Ignatius Antiochenus,tlg1443,8396,790,2,0.002532
"Theodoret, Bishop of Cyrus",tlg4089,153333,16094,40,0.002485
"Basil, Saint, Bishop of Caesarea",tlg2040,144429,11257,23,0.002043
Hippolytus,tlg2115,69987,4394,7,0.001593
Clemens Romanus,tlg1271,13936,1410,2,0.001418
Clement of Alexandria,tlg0555,235754,14753,18,0.001220
pseudo-Menander,tlg2022,77297,20005,14,0.000700
Eusebius,tlg2018,620546,35220,17,0.000483

In [29]:
df[df["author"].str.startswith(">Cate")]

,filename,author,title,wordcount,author_id,doc_id,raw_date,date_avr,date_probs,date_manual,provenience,tlg_epithet,clean_string,n_sentences,lemmatized_sentences,sentences_paul,sentences_paul_N
1443,tlg4102.tlg034.opp-grc1.xml,>Catenae (Novum Testamentum),Catena In Epistulam I Ad Timotheum,14122,tlg4102,tlg4102.tlg034,p. A.D. 5,6.0,"{'14.5': 0.001, '13.5': 0.002, '12.5': 0.0039,...",NaN,christian,[],ΤΩΝ τοῦ Ἀποστόλου μαθητῶν ὁ Τιμόθεος ἦν· καὶ μ...,1157,"[[ἀπόστολος, μαθητής, Τιμόθεος, εἰμί], [μαρτυρ...","[[συνετός, εἰμί, ἀκούω, Παῦλος, περιτομή, κηρύ...",36